name: Check React App
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github'
      - '.husky'
      - '.vscode'
      - '.git'
      - '.idea'
jobs:
  deploy:
    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Installing Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/yarn.lock', '**/package.json', '**/package-lock.json') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint application
        run: yarn lint
      - name: Test application
        run: yarn test